// src/react/components/FeedCreator.tsx
import { useState } from 'react';
import type { FormEvent } from 'react';

import { createFeed } from '../services/feeds';
import { useAuth } from '../state/AuthContext';
import type { Feed } from '../types';

const EMPTY_FEED: Feed = {
  title: '',
  type: 'rss',
  url: '',
};

type SaveStatus = 'idle' | 'saving' | 'success' | 'error';

export function FeedCreator() {
  const { credentials } = useAuth();
  const [feed, setFeed] = useState<Feed>(EMPTY_FEED);
  const [submitted, setSubmitted] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatus, setSaveStatus] = useState<SaveStatus>('idle');
  const isValid = Boolean(feed.title.trim() && feed.type.trim() && feed.url.trim());

  function updateFeed(field: keyof Feed, value: string) {
    setFeed((current) => ({ ...current, [field]: value }));
  }

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitted(true);

    if (!isValid || isSaving) return;

    setIsSaving(true);
    setSaveStatus('saving');

    try {
      await createFeed(feed, credentials);
      setFeed(EMPTY_FEED);
      setSubmitted(false);
      setSaveStatus('success');
    } catch {
      setSaveStatus('error');
    } finally {
      setIsSaving(false);
    }
  }

  const statusMessage = getStatusMessage(saveStatus, feed);

  return (
    <section className="creator" aria-labelledby="feed-create-title">
      <form className="creator__form" onSubmit={onSubmit} noValidate>
        <header className="creator__header">
          <h1 id="feed-create-title">Create feed</h1>
        </header>
        <div className="creator__fields">
          <CreatorField
            id="title"
            label="Title"
            type="text"
            value={feed.title}
            placeholder="Product updates"
            error="Enter a feed title."
            invalid={submitted && !feed.title.trim()}
            onChange={(value) => updateFeed('title', value)}
          />
          <CreatorField
            id="type"
            label="Type"
            type="text"
            value={feed.type}
            placeholder="rss"
            error="Enter a feed type."
            invalid={submitted && !feed.type.trim()}
            onChange={(value) => updateFeed('type', value)}
          />
          <CreatorField
            id="url"
            label="URL"
            type="url"
            value={feed.url}
            placeholder="https://example.com/feed.xml"
            error="Enter a valid feed URL."
            invalid={submitted && !feed.url.trim()}
            onChange={(value) => updateFeed('url', value)}
          />
        </div>
        <div className="creator__actions">
          {saveStatus !== 'idle' ? (
            <span className="creator__status" role={saveStatus === 'error' ? 'alert' : undefined} aria-live="polite">
              {statusMessage}
            </span>
          ) : null}
          <button type="submit" disabled={!isValid || isSaving}>
            {isSaving ? 'Saving source' : 'Create feed'}
          </button>
        </div>
      </form>
    </section>
  );
}

function CreatorField(props: {
  id: keyof Feed;
  label: string;
  type: string;
  value: string;
  placeholder: string;
  error: string;
  invalid: boolean;
  onChange: (value: string) => void;
}) {
  const errorId = `${props.id}-error`;

  return (
    <div className={`field field--${props.id}`}>
      <label htmlFor={props.id}>{props.label}</label>
      <div className="field__control">
        <input
          type={props.type}
          id={props.id}
          name={props.id}
          value={props.value}
          onChange={(event) => props.onChange(event.target.value)}
          autoComplete={props.id === 'url' ? 'url' : 'off'}
          placeholder={props.placeholder}
          aria-describedby={props.invalid ? errorId : undefined}
          aria-invalid={props.invalid ? 'true' : undefined}
          required
        />
      </div>
      {props.invalid ? <p id={errorId} className="field__error">{props.error}</p> : null}
    </div>
  );
}

function getStatusMessage(saveStatus: SaveStatus, feed: Feed): string {
  if (saveStatus === 'saving') return 'Saving source...';
  if (saveStatus === 'success') return 'Feed source saved.';
  if (saveStatus === 'error') return 'Could not save feed source. Try again.';
  return feed.title && feed.type && feed.url ? 'Ready to save' : 'Complete all fields';
}

// src/app/components/feed-creator/feed-creator.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';
import { finalize } from 'rxjs';

import { IFeed } from 'src/app/models/feed';
import { FeedsService } from 'src/app/services/feeds.service';

const EMPTY_FEED: IFeed = {
  title: '',
  type: 'rss',
  url: '',
};

@Component({
  selector: 'app-feed-creator',
  templateUrl: './feed-creator.component.html',
  styleUrls: ['./feed-creator.component.scss'],
  standalone: false,
})
export class FeedCreatorComponent {
  feed: IFeed = { ...EMPTY_FEED };
  isSaving = false;
  saveStatus: 'idle' | 'saving' | 'success' | 'error' = 'idle';

  constructor(private readonly feedService: FeedsService) {}

  onSubmit(form: NgForm): void {
    if (form.invalid || this.isSaving) {
      return;
    }

    this.isSaving = true;
    this.saveStatus = 'saving';
    this.feedService
      .create(this.feed)
      .pipe(finalize(() => (this.isSaving = false)))
      .subscribe({
        next: () => {
          this.resetForm(form);
          this.saveStatus = 'success';
        },
        error: () => {
          this.saveStatus = 'error';
        },
      });
  }

  get statusMessage(): string {
    if (this.saveStatus === 'saving') {
      return 'Saving source...';
    }

    if (this.saveStatus === 'success') {
      return 'Feed source saved.';
    }

    if (this.saveStatus === 'error') {
      return 'Could not save feed source. Try again.';
    }

    return this.feed.title && this.feed.type && this.feed.url
      ? 'Ready to save'
      : 'Complete all fields';
  }

  private resetForm(form: NgForm): void {
    this.feed = { ...EMPTY_FEED };
    form.resetForm(this.feed);
  }
}

<section class="creator" aria-labelledby="feed-create-title">
  <form class="creator__form" #feedForm="ngForm" (ngSubmit)="onSubmit(feedForm)">
    <header class="creator__header">
      <h1 id="feed-create-title">Create feed</h1>
      <p>Add a source with a clear name and feed URL.</p>
    </header>

    <div class="creator__fields">
      <div class="field field--title">
        <label for="title">Title</label>
        <div class="field__control">
          <span class="field__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" focusable="false" width="21" height="21" fill="currentColor">
              <path d="M7 3h10a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm0 2v14h10V5H7Zm3 4h5v2h-5V9Zm0 4h5v2h-5v-2Z" />
            </svg>
          </span>
          <input
            type="text"
            id="title"
            name="title"
            [(ngModel)]="feed.title"
            autocomplete="off"
            placeholder="Product updates"
            required
          />
        </div>
      </div>

      <div class="field">
        <label for="type">Type</label>
        <div class="field__control">
          <span class="field__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" focusable="false" width="21" height="21" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round">
              <path d="M5.5 5.5c7.2 0 13 5.8 13 13" />
              <path d="M5.5 11c4.1 0 7.5 3.4 7.5 7.5" />
              <path d="M6.2 18.4h.01" stroke-width="4" />
            </svg>
          </span>
          <input
            type="text"
            id="type"
            name="type"
            [(ngModel)]="feed.type"
            autocomplete="off"
            placeholder="rss"
            required
          />
        </div>
      </div>

      <div class="field field--url">
        <label for="url">URL</label>
        <div class="field__control">
          <span class="field__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" focusable="false" width="21" height="21" fill="currentColor">
              <path d="M10.6 13.4a1.5 1.5 0 0 1 0-2.1l3.9-3.9a3 3 0 0 1 4.2 4.2l-2.1 2.1a1 1 0 0 0 1.4 1.4l2.1-2.1a5 5 0 0 0-7.1-7.1L9.2 9.9a3.5 3.5 0 0 0 0 5 1 1 0 1 0 1.4-1.5Zm2.8-2.8a1.5 1.5 0 0 1 0 2.1l-3.9 3.9a3 3 0 0 1-4.2-4.2l2.1-2.1A1 1 0 0 0 6 8.9L3.9 11a5 5 0 0 0 7.1 7.1l3.9-3.9a3.5 3.5 0 0 0 0-5 1 1 0 1 0-1.5 1.4Z" />
            </svg>
          </span>
          <input
            type="url"
            id="url"
            name="url"
            [(ngModel)]="feed.url"
            autocomplete="url"
            placeholder="https://example.com/feed.xml"
            required
          />
        </div>
      </div>
    </div>

    <div class="creator__actions">
      <span class="creator__status" [attr.role]="saveStatus === 'error' ? 'alert' : null" aria-live="polite">
        <svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2.4">
          <circle cx="12" cy="12" r="9" />
          <path d="M12 10v6M12 7h.01" />
        </svg>
        {{ statusMessage }}
      </span>
      <button type="submit" [disabled]="!feedForm.valid || isSaving">
        <svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2.4">
          <circle cx="12" cy="12" r="8.5" />
          <path d="M12 8v8M8 12h8" />
        </svg>
        {{ isSaving ? 'Saving source' : 'Create feed' }}
      </button>
    </div>
  </form>
</section>
