// src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';

import { FeedSearchService } from 'src/app/services/feed-search.service';

@Component({
    selector: 'app-navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss'],
    standalone: false
})
export class NavbarComponent {
  constructor(public readonly feedSearchService: FeedSearchService) {}

  onSearchInput(event: Event): void {
    this.feedSearchService.searchTerm = (event.target as HTMLInputElement).value;
  }
}

<nav class="nav nav-live-leftbar" aria-label="Primary navigation">
  <a class="nav-live-leftbar__brand" routerLink="/" aria-label="GKFEED home">GKFEED</a>
  <span class="nav-live-leftbar__links" aria-label="Feed sections">
    <a class="nav-live-leftbar__link" routerLink="/" routerLinkActive="nav-live-leftbar__link--active" [routerLinkActiveOptions]="{ exact: true }" ariaCurrentWhenActive="page">List</a>
    <a class="nav-live-leftbar__link" routerLink="/create" routerLinkActive="nav-live-leftbar__link--active" ariaCurrentWhenActive="page">Create</a>
    <a class="nav-live-leftbar__link" routerLink="/login" routerLinkActive="nav-live-leftbar__link--active" ariaCurrentWhenActive="page">Login</a>
  </span>
  @if (showSearch) {
    <input
      class="nav-live-leftbar__search"
      type="search"
      placeholder="Search feeds"
      aria-label="Search feeds"
      [value]="feedSearchService.searchTerm"
      (input)="onSearchInput($event)"
      (search)="onSearchInput($event)"
    />
  }
</nav>

// src/react/components/Navbar.tsx
import { NavLink, useLocation } from 'react-router-dom';

import { useFeedSearch } from '../state/FeedSearchContext';

export function Navbar() {
  const location = useLocation();
  const { searchTerm, setSearchTerm } = useFeedSearch();
  const showSearch = location.pathname === '/';

  return (
    <nav className="nav" aria-label="Primary navigation">
      <NavLink className="nav-live-leftbar__brand" to="/" aria-label="GKFEED home">GKFEED</NavLink>
      <span className="nav-live-leftbar__links" aria-label="Feed sections">
        <NavLink className={({ isActive }) => `nav-live-leftbar__link${isActive ? ' nav-live-leftbar__link--active' : ''}`} to="/" end>List</NavLink>
        <NavLink className={({ isActive }) => `nav-live-leftbar__link${isActive ? ' nav-live-leftbar__link--active' : ''}`} to="/create">Create</NavLink>
        <NavLink className={({ isActive }) => `nav-live-leftbar__link${isActive ? ' nav-live-leftbar__link--active' : ''}`} to="/login">Login</NavLink>
      </span>
      {showSearch ? (
        <input
          className="nav-live-leftbar__search"
          type="search"
          placeholder="Search feeds"
          aria-label="Search feeds"
          value={searchTerm}
          onChange={(event) => setSearchTerm(event.target.value)}
        />
      ) : null}
    </nav>
  );
}
