// src/react/components/FeedsList.tsx
import { useDeferredValue, useMemo } from 'react';
import { Link } from 'react-router-dom';

import { useAsyncLoad } from '../hooks/useAsyncLoad';
import { useDebouncedValue } from '../hooks/useDebouncedValue';
import { getAllFeeds } from '../services/feeds';
import { useAuth } from '../state/AuthContext';
import { useFeedSearch } from '../state/FeedSearchContext';
import type { Credentials, Feed } from '../types';
import { FeedCard } from './FeedCard';

const SEARCH_DEBOUNCE_MS = 80;
const SKELETON_ITEMS = [1, 2, 3] as const;

interface FeedLoadResult {
  feeds: Feed[];
  errorMessage?: string;
}

export function FeedsList() {
  const { credentials } = useAuth();
  const { searchTerm } = useFeedSearch();
  const deferredSearchTerm = useDeferredValue(searchTerm);
  const settledSearchTerm = useDebouncedValue(deferredSearchTerm, SEARCH_DEBOUNCE_MS);
  const { feeds, errorMessage, isLoading, retry } = useFeeds(credentials);
  const displayQuery = settledSearchTerm.trim();
  const normalizedQuery = displayQuery.toLowerCase();
  const filteredFeeds = useMemo(() => filterFeeds(feeds, normalizedQuery), [feeds, normalizedQuery]);
  const resultsAnnouncement = isLoading ? 'Loading feeds.' : getResultsAnnouncement(filteredFeeds.length, displayQuery);

  return (
    <div className="container">
      <p className="sr-only" role="status" aria-live="polite" aria-atomic="true">
        {resultsAnnouncement}
      </p>
      {isLoading ? (
        <div className="loading" role="status" aria-live="polite" aria-label="Loading feeds">
          {SKELETON_ITEMS.map((item) => (
            <div key={item} className="feed-skeleton" aria-hidden="true">
              <span className="skeleton-line skeleton-title" />
              <span className="skeleton-line" />
              <span className="skeleton-line skeleton-url" />
            </div>
          ))}
          <span className="sr-only">Loading feeds...</span>
        </div>
      ) : errorMessage ? (
        <div className="empty">
          <span role="alert">{errorMessage}</span>
          <button type="button" className="secondary" onClick={retry}>Try again</button>
        </div>
      ) : filteredFeeds.length ? (
        filteredFeeds.map((feed) => <FeedCard key={feed.id} feed={feed} />)
      ) : (
        <p className="empty">
          {normalizedQuery ? 'No matching feeds.' : <>No feeds yet. <Link to="/create">Create one</Link>.</>}
        </p>
      )}
    </div>
  );
}

function getResultsAnnouncement(count: number, query = ''): string {
  const feedLabel = count === 1 ? 'feed' : 'feeds';

  if (!query) return `Showing ${count} ${feedLabel}.`;

  return count === 0
    ? `No feeds found for search term ${query}.`
    : `${count} ${feedLabel} found for search term ${query}.`;
}

function useFeeds(credentials: Credentials | null) {
  const { result, isLoading, retry } = useAsyncLoad(() => loadFeeds(credentials), [credentials]);
  const { feeds = [], errorMessage = '' } = result ?? {};

  return {
    feeds,
    errorMessage,
    isLoading,
    retry,
  };
}

async function loadFeeds(credentials: Credentials | null): Promise<FeedLoadResult> {
  try {
    return { feeds: await getAllFeeds(credentials) };
  } catch (error) {
    return { feeds: [], errorMessage: getLoadErrorMessage(error) };
  }
}

function filterFeeds(feeds: Feed[], normalizedQuery: string): Feed[] {
  if (!normalizedQuery) return feeds;

  return feeds.filter((feed) => (
    `${feed.title} ${feed.type} ${feed.url}`.toLowerCase().includes(normalizedQuery)
  ));
}

function getLoadErrorMessage(error: unknown): string {
  return isStatusError(error) && error.status === 401
    ? 'Unable to load feeds. Log in and try again.'
    : 'Unable to load feeds. Check your connection and try again.';
}

function isStatusError(error: unknown): error is Error & { status: number } {
  return error instanceof Error
    && 'status' in error
    && typeof error.status === 'number';
}

// src/app/components/feeds-list/feeds-list.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnDestroy, OnInit } from '@angular/core';
import { distinctUntilChanged, finalize, Subscription } from 'rxjs';

import { IFeed } from 'src/app/models/feed';
import { FeedSearchService } from 'src/app/services/feed-search.service';
import { FeedsService } from 'src/app/services/feeds.service';

interface SearchableFeed {
  feed: IFeed;
  text: string;
}

@Component({
  selector: 'app-feeds-list',
  templateUrl: './feeds-list.component.html',
  styleUrls: ['./feeds-list.component.scss'],
  standalone: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FeedsListComponent implements OnDestroy, OnInit {
  feeds: IFeed[] = [];
  filteredFeeds: IFeed[] = [];
  isLoading = true;
  errorMessage = '';
  resultsAnnouncement = '';
  private searchableFeeds: SearchableFeed[] = [];
  private searchTerm = '';
  private readonly subscription = new Subscription();

  constructor(
    private readonly feedsService: FeedsService,
    private readonly feedSearchService: FeedSearchService,
    private readonly changeDetectorRef: ChangeDetectorRef,
  ) {}

  ngOnInit(): void {
    this.errorMessage = '';

    this.subscription.add(
      this.feedSearchService.searchTerm$
        .pipe(distinctUntilChanged())
        .subscribe((searchTerm) => {
          this.searchTerm = searchTerm;
          this.updateFilteredFeeds();
          this.changeDetectorRef.markForCheck();
        }),
    );

    this.subscription.add(
      this.feedsService
        .getAll()
        .pipe(
          finalize(() => {
            this.isLoading = false;
            this.changeDetectorRef.markForCheck();
          }),
        )
        .subscribe({
          next: (feeds) => {
            this.feeds = feeds;
            this.searchableFeeds = feeds.map((feed) => ({
              feed,
              text: `${feed.title} ${feed.type} ${feed.url}`.toLowerCase(),
            }));
            this.updateFilteredFeeds();
            this.changeDetectorRef.markForCheck();
          },
          error: (error: unknown) => {
            this.errorMessage = this.getLoadErrorMessage(error);
            this.changeDetectorRef.markForCheck();
          },
        }),
    );
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  trackByFeedId(_: number, feed: IFeed): number | undefined {
    return feed.id;
  }

  private updateFilteredFeeds(): void {
    const query = this.searchTerm.trim().toLowerCase();

    if (!query) {
      this.filteredFeeds = this.feeds;
      this.resultsAnnouncement = this.getResultsAnnouncement(this.filteredFeeds.length);
      return;
    }

    this.filteredFeeds = this.searchableFeeds
      .filter((searchableFeed) => searchableFeed.text.includes(query))
      .map((searchableFeed) => searchableFeed.feed);
    this.resultsAnnouncement = this.getResultsAnnouncement(this.filteredFeeds.length, query);
  }

  private getResultsAnnouncement(count: number, query = ''): string {
    const feedLabel = count === 1 ? 'feed' : 'feeds';

    if (!query) {
      return `Showing ${count} ${feedLabel}.`;
    }

    return count === 0
      ? `No feeds found for search term ${query}.`
      : `${count} ${feedLabel} found for search term ${query}.`;
  }

  private getLoadErrorMessage(error: unknown): string {
    if (error instanceof HttpErrorResponse && error.status === 401) {
      return 'Unable to load feeds. Log in and try again.';
    }

    return 'Unable to load feeds. Check your connection and try again.';
  }
}

<div class="container">
  <p class="sr-only" role="status" aria-live="polite" aria-atomic="true">
    {{ resultsAnnouncement }}
  </p>

  @if (isLoading) {
    <div class="loading" role="status" aria-live="polite" aria-label="Loading feeds">
      @for (item of [1, 2, 3]; track item) {
        <div class="feed-skeleton" aria-hidden="true">
          <span class="skeleton-line skeleton-title"></span>
          <span class="skeleton-line"></span>
          <span class="skeleton-line skeleton-url"></span>
        </div>
      }
      <span class="sr-only">Loading feeds...</span>
    </div>
  } @else if (errorMessage) {
    <p class="empty" role="alert">{{ errorMessage }}</p>
  } @else {
    @for (feed of filteredFeeds; track feed.id) {
      <app-feed-card [feed]="feed"></app-feed-card>
    } @empty {
      <p class="empty">No feeds found.</p>
    }
  }
</div>
