// src/react/pages/FeedPage.tsx
import { useCallback } from 'react';
import type { ReactNode } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate, useParams } from 'react-router';

import '../../styles/actions.css';
import '../../styles/feeds.css';
import { FeedCard } from '../components/FeedCard';
import {
  useFeedPageModel,
  type FeedDeleteStatus,
} from '../adapters/feeds/useFeedPageModel';
import { getRequestErrorMessage } from '../services/authError';

export function FeedPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const navigate = useNavigate();
  const handleDeleted = useCallback(() => navigate('/'), [navigate]);
  const {
    feed,
    loadStatus,
    loadError,
    deleteStatus,
    requestDelete,
    cancelDelete,
    deleteFeed,
    retryLoad,
  } = useFeedPageModel(id, handleDeleted);

  let content: ReactNode = null;

  if (loadStatus === 'loading') {
    content = <p className="status" aria-live="polite">{t('feedDetails.loading')}</p>;
  } else if (loadStatus === 'not-found' || loadStatus === 'error') {
    content = (
      <LoadErrorState
        message={loadStatus === 'not-found'
          ? t('feedDetails.notFound')
          : getRequestErrorMessage(loadError, t, 'feedDetails.loadError')}
        canRetry={loadStatus === 'error'}
        onRetry={retryLoad}
      />
    );
  } else if (feed) {
    content = (
      <>
        <FeedCard feed={feed} asLink={false} />
          <DeleteActions
          deleteStatus={deleteStatus}
          onRequestDelete={requestDelete}
          onCancelDelete={cancelDelete}
          onDelete={deleteFeed}
        />
      </>
    );
  }

  return (
    <section className="container" aria-labelledby="feed-page-title">
      <h1 id="feed-page-title" className="page-title">{t('pages.feedDetails')}</h1>
      {content}
    </section>
  );
}

function LoadErrorState({ message, canRetry, onRetry }: { message: string; canRetry: boolean; onRetry: () => void }) {
  const { t } = useTranslation();

  return (
    <>
      <p className="status status--error" role="alert">{message}</p>
      {canRetry ? (
        <button type="button" className="secondary" onClick={onRetry}>{t('live.tryAgain')}</button>
      ) : null}
    </>
  );
}

function DeleteActions({
  deleteStatus,
  onRequestDelete,
  onCancelDelete,
  onDelete,
}: {
  deleteStatus: FeedDeleteStatus;
  onRequestDelete: () => void;
  onCancelDelete: () => void;
  onDelete: () => void;
}) {
  const { t } = useTranslation();
  const isConfirmingDelete = deleteStatus !== 'idle';
  const isDeleting = deleteStatus === 'deleting';

  return (
    <div className="actions">
      {isConfirmingDelete ? (
        <>
          <p className="status" id="delete-confirmation">{t('feedDetails.deleteQuestion')}</p>
          <div className="actions__confirm" aria-describedby="delete-confirmation">
            <button type="button" className="secondary" onClick={onCancelDelete} disabled={isDeleting} autoFocus>
              {t('auth.cancel')}
            </button>
            <button type="button" onClick={onDelete} className="delete" disabled={isDeleting}>
              {isDeleting ? t('feedDetails.deleting') : t('feedDetails.deleteSource')}
            </button>
          </div>
        </>
      ) : (
        <button type="button" onClick={onRequestDelete} className="delete" disabled={isDeleting}>
          {t('feedDetails.delete')}
        </button>
      )}
      {deleteStatus === 'error' ? (
        <p className="status status--error" role="alert">{t('feedDetails.deleteError')}</p>
      ) : isDeleting ? (
        <p className="status" aria-live="polite">{t('feedDetails.deletingSource')}</p>
      ) : null}
    </div>
  );
}

// src/app/pages/feed-page/feed-page.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { IFeed } from 'src/app/models/feed';
import { FeedsService } from 'src/app/services/feeds.service';

@Component({
    selector: 'app-feed-page',
    templateUrl: './feed-page.component.html',
    styleUrls: ['./feed-page.component.scss'],
    standalone: false
})
export class FeedPageComponent {
  constructor(
    public route: ActivatedRoute,
    public router: Router,
    public feedsService: FeedsService,
  ) {}
  id!: number;
  feed!: IFeed;

  onClick() {
    this.feedsService.deleteFeedById(this.id).subscribe();
    this.router.navigate(['/']);
  }

  ngOnInit() {
    this.route.params.subscribe((params) => {
      this.id = parseInt(params['id']);
    });

    this.feedsService.getFeedById(this.id).subscribe((feed) => {
      if (feed) {
        this.feed = feed;
      }
      // TODO: errorService can't find feed by this id
    });
  }
}

<section class="container" aria-labelledby="feed-page-title">
  <h1 id="feed-page-title" class="page-title">Feed source details</h1>

  @if (isLoading) {
    <p class="status" aria-live="polite">Loading feed source</p>
  } @else if (loadError) {
    <p class="status status--error" role="alert">{{ loadError }}</p>
  } @else if (feed) {
    <app-feed-card [feed]="feed" [asLink]="false"></app-feed-card>
    <div class="actions">
      @if (isConfirmingDelete) {
        <p class="status" id="delete-confirmation">Delete this feed source? This cannot be undone.</p>
        <div class="actions__confirm" aria-describedby="delete-confirmation">
          <button type="button" class="secondary" (click)="cancelDelete()" [disabled]="isDeleting">
            Cancel
          </button>
          <button type="button" (click)="deleteFeed()" class="delete" [disabled]="isDeleting">
            {{ isDeleting ? 'Deleting...' : 'Delete feed source' }}
          </button>
        </div>
      } @else {
        <button type="button" (click)="requestDelete()" class="delete" [disabled]="isDeleting">
          Delete
        </button>
      }
      @if (deleteError) {
        <p class="status status--error" role="alert">{{ deleteError }}</p>
      } @else if (isDeleting) {
        <p class="status" aria-live="polite">Deleting feed source</p>
      }
    </div>
  }
</section>
