// src/react/pages/LoginPage.tsx
import { useState } from 'react';
import type { FormEvent } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

import { LockIcon, UserIcon } from '../components/Icons';
import { useAuth } from '../state/AuthContext';
import { getRedirectTarget } from '../state/routes';

const EMPTY_FORM = { username: '', password: '' };
const FIELDS = [
  { name: 'username', label: 'Username', type: 'text', autoComplete: 'username', placeholder: 'gakawarstone', Icon: UserIcon },
  { name: 'password', label: 'Password', type: 'password', autoComplete: 'current-password', placeholder: undefined, Icon: LockIcon },
] as const;

export function LoginPage() {
  const { credentials, saveCredentials, clearCredentials } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const [form, setForm] = useState(EMPTY_FORM);
  const [submitted, setSubmitted] = useState(false);
  const savedUsername = credentials?.username ?? '';
  const isValid = Boolean(form.username.trim() && form.password);
  const redirectTo = getRedirectTarget(location.state);

  function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitted(true);
    if (!isValid) return;

    saveCredentials({ ...form, username: form.username.trim() });
    setForm(EMPTY_FORM);
    setSubmitted(false);
    navigate(redirectTo, { replace: true });
  }

  return (
    <section className="login" aria-labelledby="login-title">
      {savedUsername ? (
        <div className="login__form login__form--saved">
          <header className="login__header">
            <h1 id="login-title">Account access</h1>
          </header>
          <div className="field__control" role="status">
            <span className="field__icon" aria-hidden="true"><UserIcon /></span>
            <span>Logged in as <strong>{savedUsername}</strong></span>
          </div>
          <div className="login__actions">
            <button type="button" className="danger" onClick={clearCredentials} autoFocus>Log out</button>
          </div>
        </div>
      ) : (
        <form className="login__form" onSubmit={onSubmit} noValidate>
          <header className="login__header">
            <p className="login__eyebrow">Account access</p>
            <h1 id="login-title">Sign in to GKFEED</h1>
          </header>
          <div className="login__fields">
            {FIELDS.map(({ name, label, Icon, ...inputProps }) => {
              const invalid = submitted && !form[name].trim();
              const helpId = `${name}-help`;
              const errorId = `${name}-error`;

              return (
                <div className="field" key={name}>
                  <label htmlFor={name}>{label}</label>
                  <div className="field__control">
                    <span className="field__icon" aria-hidden="true"><Icon /></span>
                    <input
                      {...inputProps}
                      id={name}
                      name={name}
                      value={form[name]}
                      onChange={(event) => setForm((current) => ({ ...current, [name]: event.target.value }))}
                      autoFocus={name === 'username'}
                      aria-describedby={`${helpId}${invalid ? ` ${errorId}` : ''}`}
                      aria-invalid={invalid || undefined}
                      required
                    />
                  </div>
                  <p id={helpId} className="field__hint">Required. Enter your {name}.</p>
                  {invalid ? <p id={errorId} className="field__error" role="alert">Enter your {name}.</p> : null}
                </div>
              );
            })}
          </div>
          <div className="login__actions">
            <span className="login__status" aria-live="polite">{isValid ? 'Ready to save' : 'Enter credentials'}</span>
            <button type="submit">Save login</button>
          </div>
        </form>
      )}
    </section>
  );
}

// src/app/pages/login-page/login-page.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-login-page',
    templateUrl: './login-page.component.html',
    styleUrl: './login-page.component.scss',
    standalone: false
})
export class LoginPageComponent {
  username: string = '';
  password: string = '';
  show: string | null =
    localStorage.getItem('username') + ' : ' + localStorage.getItem('password');

  onSubmit() {
    localStorage.setItem('username', this.username);
    localStorage.setItem('password', this.password);
    this.show =
      localStorage.getItem('username') +
      ' : ' +
      localStorage.getItem('password');
  }
}

<section class="login" aria-labelledby="login-title">
  @if (savedUsername) {
    <div class="login__form login__form--saved">
      <header class="login__header">
        <h1 id="login-title">Account access</h1>
      </header>

      <div class="field__control">
        <span class="field__icon" aria-hidden="true">
          <svg viewBox="0 0 24 24" focusable="false" width="22" height="22" fill="currentColor">
            <path d="M12 12a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9Zm0 2c-4.1 0-7.5 2.3-7.5 5.1 0 1 .8 1.9 1.9 1.9h11.2c1.1 0 1.9-.9 1.9-1.9 0-2.8-3.4-5.1-7.5-5.1Z" />
          </svg>
        </span>
        <span>Logged in as <strong>{{ savedUsername }}</strong></span>
      </div>

      <div class="login__actions">
        <button type="button" class="danger" (click)="onLogout()">Log out</button>
      </div>
    </div>
  } @else {
  <form class="login__form" #userForm="ngForm" (ngSubmit)="onSubmit(userForm)">
    <header class="login__header">
      <p class="login__eyebrow">Account access</p>
      <h1 id="login-title">Sign in to GKFEED</h1>
    </header>

    <div class="login__fields">
      <div class="field">
        <label for="username">Username</label>
        <div class="field__control">
          <span class="field__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" focusable="false" width="21" height="21" fill="currentColor">
              <path d="M12 12a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9Zm0 2c-4.1 0-7.5 2.3-7.5 5.1 0 1 .8 1.9 1.9 1.9h11.2c1.1 0 1.9-.9 1.9-1.9 0-2.8-3.4-5.1-7.5-5.1Z" />
            </svg>
          </span>
          <input
            #usernameCtrl="ngModel"
            type="text"
            id="username"
            name="username"
            [(ngModel)]="credentials.username"
            autocomplete="username"
            placeholder="gakawarstone"
            [attr.aria-describedby]="usernameCtrl.invalid && (usernameCtrl.touched || userForm.submitted) ? 'username-help username-error' : 'username-help'"
            [attr.aria-invalid]="usernameCtrl.invalid && (usernameCtrl.touched || userForm.submitted) ? 'true' : null"
            required
          />
        </div>
        <p id="username-help" class="field__hint">Required. Enter your username.</p>
        @if (usernameCtrl.invalid && (usernameCtrl.touched || userForm.submitted)) {
          <p id="username-error" class="field__error">Enter your username.</p>
        }
      </div>

      <div class="field">
        <label for="password">Password</label>
        <div class="field__control">
          <span class="field__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" focusable="false" width="21" height="21" fill="currentColor">
              <path d="M7 10V8a5 5 0 0 1 10 0v2h.5A2.5 2.5 0 0 1 20 12.5v6A2.5 2.5 0 0 1 17.5 21h-11A2.5 2.5 0 0 1 4 18.5v-6A2.5 2.5 0 0 1 6.5 10H7Zm2 0h6V8a3 3 0 1 0-6 0v2Zm3 4a1.5 1.5 0 0 0-1 2.6V18h2v-1.4A1.5 1.5 0 0 0 12 14Z" />
            </svg>
          </span>
          <input
            #passwordCtrl="ngModel"
            type="password"
            id="password"
            name="password"
            [(ngModel)]="credentials.password"
            autocomplete="current-password"
            [attr.aria-describedby]="passwordCtrl.invalid && (passwordCtrl.touched || userForm.submitted) ? 'password-help password-error' : 'password-help'"
            [attr.aria-invalid]="passwordCtrl.invalid && (passwordCtrl.touched || userForm.submitted) ? 'true' : null"
            required
          />
        </div>
        <p id="password-help" class="field__hint">Required. Enter your password.</p>
        @if (passwordCtrl.invalid && (passwordCtrl.touched || userForm.submitted)) {
          <p id="password-error" class="field__error">Enter your password.</p>
        }
      </div>
    </div>

    <div class="login__actions">
      <span class="login__status" aria-live="polite">
        {{ userForm.valid ? 'Ready to save' : 'Enter credentials' }}
      </span>
      <button type="submit" [disabled]="!userForm.valid">Save login</button>
    </div>
  </form>
  }
</section>
